<?php

namespace AppBundle\Repository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllComments($id)
    {
        $query=$this->createQueryBuilder('c')->select('c')
            ->join('c.article', 'a')
            ->where('a .id = :id')
            ->orderBy('c.id', 'DESC')
            ->setParameter('id', $id);

        $results = $query->getQuery()->getResult();

        return $results;
    }



    public function deleteComment($id)
    {
        $qb = $this->createQueryBuilder('c');
        $q = $qb->delete('AppBundle:Avis', 'c')
            ->where('c.id ='.$id)
            ->getQuery();
        $q->execute();
    }

}
