<?php

namespace AppBundle\Repository;

/**
 * BonPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
