<?php

namespace AppBundle\Repository;

/**
 * EnchereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnchereRepository extends \Doctrine\ORM\EntityRepository
{
}
